<?php

namespace UserBundle\Repository;

/**
 * ProgettiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgettiRepository extends \Doctrine\ORM\EntityRepository
{
}
